GET http://127.0.0.1:5000 HTTP/1.1

###

GET http://127.0.0.1:5000/users HTTP/1.1

###

GET http://127.0.0.1:5000/users/test/info HTTP/1.1

###

POST http://127.0.0.1:5000/users HTTP/1.1
content-type: application/json

{
	"username": "test3",
	"password": "test123",
	"email": "jford11@hawk.iit.edu"
}

###

DELETE http://127.0.0.1:5000/users HTTP/1.1
